// File: script.js (V16.0 - Custom Confirm)

// GANTI DENGAN LINK GOOGLE SHEET CSV KAMU
const googleSheetURL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRVm7A6LvL2chRGyir6vqY-4hcgGLCHIeL7WdWb5NkET9aihdc3py86gJfv2GGhPJ8OeyWmVRBUivf2/pub?output=csv';

let databaseProduk = {};
let daftarNamaProduk = [];

// Nama key di localStorage
const KEY_RIWAYAT = 'app_data_h';
const KEY_PENGATURAN = 'app_data_s';
const KEY_TEMA = 'app_data_t';
const KEY_PRODUK_CACHE = 'app_data_p_cache';

document.addEventListener('DOMContentLoaded', () => {

    // --- Ambil Elemen Loading & Tombol Tema ---
    const loadingPage = document.querySelector('.loading-page');
    const tombolTema = document.getElementById('tombol-tema');

    // --- Load Tema Segera ---
    function loadTema() {
        const temaTersimpan = localStorage.getItem(KEY_TEMA);
        if (temaTersimpan === 'dark') {
            document.body.classList.add('dark-mode');
            if (tombolTema) tombolTema.textContent = '🌙';
        } else {
            document.body.classList.remove('dark-mode');
            if (tombolTema) tombolTema.textContent = '☀️';
        }
    }
    loadTema();

    // --- Ambil Elemen Custom Alert ---
    const customAlertOverlay = document.getElementById('custom-alert-overlay');
    const customAlertBox = document.getElementById('custom-alert-box');
    const customAlertTitle = document.getElementById('custom-alert-title');
    const customAlertMessage = document.getElementById('custom-alert-message');
    const customAlertCloseBtn = document.getElementById('custom-alert-close');
    const customAlertOkBtn = document.getElementById('custom-alert-ok');

    // --- Ambil Elemen Custom Confirm ---
    const customConfirmOverlay = document.getElementById('custom-confirm-overlay');
    const customConfirmBox = document.getElementById('custom-confirm-box');
    const customConfirmTitle = document.getElementById('custom-confirm-title');
    const customConfirmMessage = document.getElementById('custom-confirm-message');
    const customConfirmCloseBtn = document.getElementById('custom-confirm-close');
    const customConfirmOkBtn = document.getElementById('custom-confirm-ok');
    const customConfirmCancelBtn = document.getElementById('custom-confirm-cancel');

    // --- Fungsi Custom Alert ---
    function showCustomAlert(message, type = 'info') {
        if (!customAlertOverlay || !customAlertBox || !customAlertMessage || !customAlertTitle || !customAlertOkBtn || !customAlertCloseBtn) { console.error("Elemen custom alert tidak ditemukan! Fallback ke alert biasa."); alert(message); return; }
        customAlertMessage.textContent = message;
        if (type === 'error') { customAlertTitle.textContent = 'Error!'; customAlertBox.classList.add('custom-alert--error'); }
        else { customAlertTitle.textContent = 'Informasi'; customAlertBox.classList.remove('custom-alert--error'); }
        customAlertOverlay.classList.remove('hidden'); customAlertBox.classList.remove('hidden');
        const closeAlert = () => { customAlertOverlay.classList.add('hidden'); customAlertBox.classList.add('hidden'); customAlertOkBtn.removeEventListener('click', closeAlert); customAlertCloseBtn.removeEventListener('click', closeAlert); customAlertOverlay.removeEventListener('click', closeAlert); };
        customAlertOkBtn.addEventListener('click', closeAlert); customAlertCloseBtn.addEventListener('click', closeAlert); customAlertOverlay.addEventListener('click', closeAlert);
    }

    // --- Fungsi Custom Confirm (Pakai Promise) ---
    function showCustomConfirm(message, title = 'Konfirmasi') {
        return new Promise((resolve) => {
            if (!customConfirmOverlay || !customConfirmBox || !customConfirmMessage || !customConfirmTitle || !customConfirmOkBtn || !customConfirmCancelBtn || !customConfirmCloseBtn) { console.error("Elemen custom confirm tidak ditemukan! Fallback ke confirm biasa."); resolve(confirm(message)); return; }
            customConfirmMessage.textContent = message; customConfirmTitle.textContent = title;
            customConfirmOverlay.classList.remove('hidden'); customConfirmBox.classList.remove('hidden');
            const removeListeners = () => { customConfirmOkBtn.removeEventListener('click', handleOk); customConfirmCancelBtn.removeEventListener('click', handleCancel); customConfirmCloseBtn.removeEventListener('click', handleCancel); customConfirmOverlay.removeEventListener('click', handleCancel); };
            const handleOk = () => { removeListeners(); customConfirmOverlay.classList.add('hidden'); customConfirmBox.classList.add('hidden'); resolve(true); };
            const handleCancel = () => { removeListeners(); customConfirmOverlay.classList.add('hidden'); customConfirmBox.classList.add('hidden'); resolve(false); };
            customConfirmOkBtn.addEventListener('click', handleOk); customConfirmCancelBtn.addEventListener('click', handleCancel); customConfirmCloseBtn.addEventListener('click', handleCancel); customConfirmOverlay.addEventListener('click', handleCancel);
        });
    }

    // --- Definisikan Fungsi Lainnya ---
    function getItemHTML(nomorBarang) { return ` <div class="card__header"> <h4>Barang ${nomorBarang}</h4> <button type="button" class="btn-delete-item hapus-barang-btn" title="Hapus barang ini">&times;</button> </div> <div class="card__content"> <div class="input-grup"> <label>Nama Barang:</label> <div class="search-container"> <input type="text" class="nama-barang-search" placeholder="Ketik & Pilih Produk..."> <div class="search-results hidden"></div> </div> </div> <div class="grup-hg"> <label>Harga Grosir (HG):</label> <input type="text" class="harga-grosir" placeholder="Otomatis"> </div> <div class="input-grup"> <label>Harga Khusus (HK):</label> <input type="text" class="harga-khusus" placeholder="Isi HK" required> </div> <div class="input-grup"> <label>Pengambilan (Qty):</label> <input type="text" class="kuantitas" placeholder="Contoh: 5 dus" required> </div> </div> `; }
    async function loadDatabase(generateBtnRef) { console.log('Mencoba mengambil data produk...'); if (generateBtnRef) { generateBtnRef.textContent = 'MEMUAT...'; generateBtnRef.disabled = true; } try { console.log('Fetching dari Google Sheet...'); const response = await fetch(googleSheetURL); if (!response.ok) throw new Error(`Gagal fetch: ${response.statusText}`); const csvData = await response.text(); console.log('Fetch berhasil. Memproses data...'); const parsedData = parseCsvData(csvData); databaseProduk = parsedData.db; daftarNamaProduk = parsedData.list; console.log('Menyimpan data ke cache localStorage...'); try { localStorage.setItem(KEY_PRODUK_CACHE, JSON.stringify(databaseProduk)); console.log('Cache berhasil disimpan.'); } catch (cacheError) { console.error('Gagal menyimpan cache:', cacheError); } console.log('Database online berhasil dimuat.'); if (generateBtnRef) { generateBtnRef.textContent = '🚀 BUAT TEKS'; generateBtnRef.disabled = false; } return true; } catch (fetchError) { console.warn('Fetch gagal:', fetchError.message, 'Mencoba memuat dari cache...'); try { const cachedDataString = localStorage.getItem(KEY_PRODUK_CACHE); if (cachedDataString) { console.log('Data cache ditemukan. Memproses...'); databaseProduk = JSON.parse(cachedDataString); daftarNamaProduk = Object.keys(databaseProduk).sort(); console.log('Database dari cache berhasil dimuat.'); showCustomAlert('INFO: Menggunakan data produk offline (cache). Hubungkan ke internet untuk update terbaru.'); if (generateBtnRef) { generateBtnRef.textContent = '🚀 BUAT TEKS'; generateBtnRef.disabled = false; } return true; } else { console.error('Cache juga kosong.'); throw new Error('Fetch gagal dan tidak ada cache.'); } } catch (cacheError) { console.error('Gagal memuat atau parse cache:', cacheError); throw new Error('Fetch gagal dan cache rusak/tidak bisa dibaca.'); } } }
    function parseCsvData(csvData) { const db = {}; const baris = csvData.split('\n'); for (let i = 1; i < baris.length; i++) { const barisData = baris[i].trim(); if (barisData) { let nama = "", hg = "", hk = ""; const pemisah1 = barisData.lastIndexOf(','); const col_Last = barisData.substring(pemisah1 + 1).trim().replace(/"/g, ''); const sisa1 = barisData.substring(0, pemisah1).trim(); if (sisa1 === "") { nama = col_Last; hg = "0"; hk = "0"; } else { const pemisah2 = sisa1.lastIndexOf(','); const col_Mid = sisa1.substring(pemisah2 + 1).trim().replace(/"/g, ''); const sisa2 = sisa1.substring(0, pemisah2).trim(); if (sisa2 === "") { if (col_Last === "" && col_Mid.length > 0) { nama = col_Mid; hg = "0"; } else { nama = col_Mid; hg = col_Last; } hk = "0"; } else { nama = sisa2.replace(/"/g, ''); hg = col_Mid; hk = col_Last; } } if (nama.toLowerCase() === 'namaproduk') continue; if (nama) { db[nama] = { hg: hg || "0", hk: hk || "0" }; } } } const list = Object.keys(db).sort(); return { db, list }; }
    function getTanggalHariIni() { const today = new Date(); const options = { timeZone: 'Asia/Jakarta', day: '2-digit', month: '2-digit', year: 'numeric' }; const parts = new Intl.DateTimeFormat('en-GB', options).formatToParts(today); let day = '', month = '', year = ''; for (const part of parts) { if (part.type === 'day') day = part.value; if (part.type === 'month') month = part.value; if (part.type === 'year') year = part.value; } return `${day}/${month}/${year}`; }
    function renumberBlocks(itemListRef) { if (!itemListRef) return; const semuaItem = itemListRef.querySelectorAll('.card--item'); semuaItem.forEach((item, index) => { const h4 = item.querySelector('h4'); if(h4) h4.textContent = `Barang ${index + 1}`; }); }
    function hapusBlokBarang(e, itemListRef) { if (!itemListRef) return; if (e.target.classList.contains('hapus-barang-btn')) { const semuaItem = itemListRef.querySelectorAll('.card--item'); if (semuaItem.length <= 1) { showCustomAlert('Tidak bisa menghapus blok barang terakhir!', 'error'); return; } const cardItem = e.target.closest('.card--item'); if (cardItem) { cardItem.remove(); renumberBlocks(itemListRef); } } }
    function tambahBarang(itemListRef) { if (!itemListRef) return; const itemBlock = document.createElement('div'); itemBlock.className = 'card card--item'; itemBlock.dataset.mode = 'standard'; const nomorBarang = itemListRef.querySelectorAll('.card--item').length + 1; itemBlock.innerHTML = getItemHTML(nomorBarang); itemListRef.appendChild(itemBlock); }
    function tampilkanHasilPencarian(searchTerm, resultsContainer) { if(!resultsContainer) return; resultsContainer.innerHTML = ''; resultsContainer.classList.remove('hidden'); const filter = searchTerm.toLowerCase(); let hasMatches = false; for (const namaProduk of daftarNamaProduk) { if (namaProduk.toLowerCase().includes(filter)) { const item = document.createElement('div'); item.className = 'result-item'; item.textContent = namaProduk; item.dataset.value = namaProduk; resultsContainer.appendChild(item); hasMatches = true; } } const customItem = document.createElement('div'); customItem.className = 'result-item'; customItem.textContent = '-- Produk Custom (Isi Manual) --'; customItem.dataset.value = '__custom'; resultsContainer.appendChild(customItem); }
    function updateTampilanBarang(itemBlock, selectedValue) { if(!itemBlock || !selectedValue) return; const searchInput = itemBlock.querySelector('.nama-barang-search'); const hgInput = itemBlock.querySelector('.harga-grosir'); const hkInput = itemBlock.querySelector('.harga-khusus'); if(!searchInput || !hgInput || !hkInput) return; if (selectedValue === "__custom") { itemBlock.dataset.mode = 'custom'; searchInput.value = ''; searchInput.placeholder = 'Ketik Nama Produk Custom...'; hgInput.value = ""; hgInput.placeholder = "Isi HG Manual"; hkInput.value = ""; hkInput.placeholder = "Isi HK (Boleh teks & simbol)"; } else { itemBlock.dataset.mode = 'standard'; searchInput.value = selectedValue; hgInput.placeholder = "Otomatis"; hkInput.placeholder = "Otomatis"; const produkData = databaseProduk[selectedValue] || { hg: "0", hk: "0" }; const hgString = produkData.hg; const hkString = produkData.hk; hgInput.value = (hgString.includes('&') || hgString.includes(',')) ? hgString : formatRupiah(hgString, false); hkInput.value = (hkString.includes('&') || hkString.includes(',')) ? hkString : formatRupiah(hkString, false); } }
    function generateTeks(e, refs) { e.preventDefault(); const format = refs.formatTypeSelect?.value; const kka = refs.kkaInput?.value; const tanggal = refs.tanggalInput?.value; const namaToko = refs.namaTokoInput?.value; const wilayah = refs.wilayahInput?.value; const marketing = refs.marketingInput?.value; if(!format || !kka || !tanggal || !namaToko || !wilayah || !marketing || !refs.itemList) { console.error("Elemen form tidak lengkap untuk generate teks."); return; } const pengajuan = { id: new Date().getTime(), namaToko, wilayah, kka, tanggal, marketing, items: [] }; let teksFinal = ""; let itemListText = ""; const semuaItem = refs.itemList.querySelectorAll('.card--item'); semuaItem.forEach((item, index) => { const mode = item.dataset.mode; const nama = item.querySelector('.nama-barang-search')?.value; const hk = item.querySelector('.harga-khusus')?.value; const hg = item.querySelector('.harga-grosir')?.value; const qty = item.querySelector('.kuantitas')?.value; if (nama && qty && hk) { pengajuan.items.push({ nama, hg: hg || 'N/A', hk, qty, isCustom: (mode === 'custom') }); if (format === 'image-format') { itemListText += `${nama}"@${qty}\n(${hk})\n`; } else { itemListText += `${index + 1}. *_${nama}_*\n- HG "@ ${hg || 'N/A'} \n- HK "@ ${hk}\n- Pengambilan : ${qty}\n\n`; } } }); if (format === 'image-format') { teksFinal = `Pengajuan Harga\nKKA : ${kka}\nTanggal : ${tanggal}\nNama. : ${namaToko}\nWilayah: ${wilayah}\n\nNama Barang\n${itemListText}\nMarketing. Direktur\n${marketing}.`; } else { teksFinal = `📌 _Pengajuan Harga_\n_KKA :_ *${kka}*\n_Tanggal :_ ${tanggal}\n_Nama Toko:_ ${namaToko}\n_Wilayah:_ ${wilayah}\n\n${itemListText}`; teksFinal += `_Marketing_       _Direktur_\n\n     ${marketing}.       `; } if (refs.hasilTeks) refs.hasilTeks.value = teksFinal; if (refs.hasilOutputSection) refs.hasilOutputSection.classList.remove('hidden'); simpanRiwayat(pengajuan); }
    function copyTeks(hasilTeksRef, tombolCopyRef) { if (!hasilTeksRef || !tombolCopyRef || !hasilTeksRef.value) { showCustomAlert('Belum ada teks untuk di-copy!', 'error'); return; } navigator.clipboard.writeText(hasilTeksRef.value).then(() => { tombolCopyRef.textContent = '✅ Berhasil!'; setTimeout(() => { tombolCopyRef.textContent = '📋 Copy'; }, 2000); }).catch(err => { console.error("Gagal menyalin:", err); showCustomAlert('Gagal menyalin teks. Coba copy manual.', 'error'); }); }
    function kirimViaWA(hasilTeksRef) { if (!hasilTeksRef || !hasilTeksRef.value) { showCustomAlert('Belum ada teks untuk dikirim! Klik "Buat Teks" dulu.', 'error'); return; } const teks = hasilTeksRef.value; const encodedTeks = encodeURIComponent(teks); const settings = getPengaturan(); const nomorWA = settings?.nomorWA; let waLink = ""; if (nomorWA) { let formattedNomor = nomorWA.replace(/[\s+()-]/g, ''); if (formattedNomor.startsWith('0')) { formattedNomor = '62' + formattedNomor.substring(1); } if (!formattedNomor.startsWith('62')) { formattedNomor = '62' + formattedNomor; } waLink = `https://api.whatsapp.com/send?phone=${formattedNomor}&text=${encodedTeks}`; } else { waLink = `https://api.whatsapp.com/send?text=${encodedTeks}`; showCustomAlert('Nomor WA Tujuan belum diatur. Membuka WA untuk pilih kontak...\n\n(Buka "Pengaturan" untuk mengatur nomor tujuan default)'); } window.open(waLink, '_blank'); }
    function formatRupiah(angka, pakaiRp = false) { let angkaString = String(angka).replace(/[^0-9]/g, ''); if (angkaString === '') return '0'; let number = Number(angkaString); if (number === 0) return '0'; let format = number.toLocaleString('id-ID'); return pakaiRp ? `Rp ${format}` : format; }
    function bukaModal(modal, overlay) { if(modal) modal.classList.remove('hidden'); if(overlay) overlay.classList.remove('hidden'); }
    function tutupModal(modalsToClose, overlay) { modalsToClose.forEach(modal => { if(modal) modal.classList.add('hidden'); }); if(overlay) overlay.classList.add('hidden'); }
    function getPengaturan() { try { const dataObfuscated = localStorage.getItem(KEY_PENGATURAN); if (!dataObfuscated) return null; const dataJson = atob(dataObfuscated); return JSON.parse(dataJson); } catch (e) { console.error("Gagal parse pengaturan:", e); localStorage.removeItem(KEY_PENGATURAN); return null; } }
    function loadPengaturan(marketingInputRef, namaSalesInputRef, nomorWaInputRef, tanggalInputRef) { const settings = getPengaturan(); if (settings) { if (settings.namaSales && marketingInputRef) { marketingInputRef.value = settings.namaSales; } if(namaSalesInputRef) namaSalesInputRef.value = settings.namaSales || ''; if(nomorWaInputRef) nomorWaInputRef.value = settings.nomorWA || ''; } else { console.warn("Pengaturan tidak ditemukan. Menggunakan nilai default."); if(namaSalesInputRef) namaSalesInputRef.value = ''; if(nomorWaInputRef) nomorWaInputRef.value = ''; } if(tanggalInputRef) tanggalInputRef.value = getTanggalHariIni(); }
    function simpanPengaturan(namaSalesInputRef, nomorWaInputRef, marketingInputRef, modalPengaturanRef, modalOverlayRef) { if(!namaSalesInputRef || !nomorWaInputRef || !marketingInputRef) return; const namaSalesDefault = namaSalesInputRef.value; const nomorWA = nomorWaInputRef.value; const settings = { namaSales: namaSalesDefault, nomorWA: nomorWA }; try { const dataJson = JSON.stringify(settings); const dataObfuscated = btoa(dataJson); localStorage.setItem(KEY_PENGATURAN, dataObfuscated); if(namaSalesDefault){ marketingInputRef.value = namaSalesDefault; } showCustomAlert('Pengaturan berhasil disimpan!'); tutupModal([modalPengaturanRef], modalOverlayRef); } catch (e) { console.error("Gagal simpan pengaturan:", e); showCustomAlert('Gagal menyimpan pengaturan.', 'error'); } }
    function getRiwayat() { try { const dataObfuscated = localStorage.getItem(KEY_RIWAYAT); if (!dataObfuscated) return []; const dataJson = atob(dataObfuscated); return JSON.parse(dataJson); } catch (e) { console.error("Gagal parse riwayat:", e); localStorage.removeItem(KEY_RIWAYAT); return []; } }
    function simpanKeStorage(riwayat) { try { const dataJson = JSON.stringify(riwayat); const dataObfuscated = btoa(dataJson); localStorage.setItem(KEY_RIWAYAT, dataObfuscated); } catch (e) { console.error("Gagal simpan riwayat:", e); showCustomAlert('Gagal menyimpan riwayat.', 'error'); } } // Tambah alert di sini
    function simpanRiwayat(pengajuan) { let riwayat = getRiwayat(); riwayat.unshift(pengajuan); riwayat = riwayat.slice(0, 50); simpanKeStorage(riwayat); }
    function hapusItemRiwayat(id, riwayatSearchInputRef, riwayatListRef) { let riwayat = getRiwayat(); const riwayatBaru = riwayat.filter(p => p.id != id); simpanKeStorage(riwayatBaru); const currentFilter = riwayatSearchInputRef ? riwayatSearchInputRef.value : ""; tampilkanRiwayat(currentFilter, riwayatListRef); }
    async function hapusSemuaRiwayat(riwayatListRef) { const confirmed = await showCustomConfirm('Apakah kamu yakin ingin menghapus SEMUA riwayat pengajuan?'); if (confirmed) { localStorage.removeItem(KEY_RIWAYAT); tampilkanRiwayat("", riwayatListRef); showCustomAlert('Semua riwayat berhasil dihapus.'); } }
    function tampilkanRiwayat(filterText = "", riwayatListRef) { if (!riwayatListRef) return; riwayatListRef.innerHTML = ''; let riwayat = getRiwayat(); if (filterText) { const filterLower = filterText.toLowerCase(); riwayat = riwayat.filter(p => p.namaToko && p.namaToko.toLowerCase().includes(filterLower)); } if (riwayat.length === 0) { riwayatListRef.innerHTML = '<p>Tidak ada riwayat pengajuan (atau tidak ada hasil pencarian).</p>'; return; } riwayat.forEach(pengajuan => { const item = document.createElement('div'); item.className = 'riwayat-item'; item.dataset.id = pengajuan.id; let itemHtml = '<ul class="riwayat-item-list">'; (pengajuan.items || []).forEach(barang => { const qtyInfo = barang.qty && String(barang.qty).trim() !== '' ? ` <strong>(${barang.qty})</strong>` : ''; itemHtml += `<li>${barang.nama || 'Nama Barang?'}${qtyInfo}</li>`; }); itemHtml += '</ul>'; item.innerHTML = `<button type="button" class="tombol-hapus-item" data-id="${pengajuan.id}">&times;</button><div class="riwayat-info"><strong>${pengajuan.namaToko || 'Toko?'}</strong><span>${pengajuan.tanggal || '?'}</span><span>${(pengajuan.items || []).length} item</span></div>${itemHtml}`; riwayatListRef.appendChild(item); }); }
    function muatDariRiwayat(id, refs) { const riwayat = getRiwayat(); const pengajuan = riwayat.find(p => p.id == id); if (!pengajuan) { showCustomAlert('Error: Riwayat tidak ditemukan.', 'error'); return; } if (!refs.namaTokoInput || !refs.wilayahInput || !refs.kkaInput || !refs.tanggalInput || !refs.marketingInput || !refs.itemList || !refs.formatTypeSelect || !refs.formPengajuan) { console.error("Referensi elemen tidak lengkap untuk muatDariRiwayat."); return; } refs.namaTokoInput.value = pengajuan.namaToko || ''; refs.wilayahInput.value = pengajuan.wilayah || ''; refs.kkaInput.value = pengajuan.kka || 'Support'; refs.tanggalInput.value = pengajuan.tanggal || getTanggalHariIni(); refs.marketingInput.value = pengajuan.marketing || ''; refs.itemList.innerHTML = ''; if (pengajuan.items && pengajuan.items.length > 0) { pengajuan.items.forEach((item) => { tambahBarang(refs.itemList); const blokBaru = refs.itemList.lastElementChild; if(blokBaru){ const searchInput = blokBaru.querySelector('.nama-barang-search'); const hgInput = blokBaru.querySelector('.harga-grosir'); const hkInput = blokBaru.querySelector('.harga-khusus'); const qtyInput = blokBaru.querySelector('.kuantitas'); if(searchInput && hgInput && hkInput && qtyInput){ if (item.isCustom) { blokBaru.dataset.mode = 'custom'; searchInput.value = item.nama || ''; searchInput.placeholder = 'Ketik Nama Produk Custom...'; } else { blokBaru.dataset.mode = 'standard'; searchInput.value = item.nama || ''; } hgInput.value = item.hg || ''; hkInput.value = item.hk || ''; qtyInput.value = item.qty || ''; } } }); } else { tambahBarang(refs.itemList); } renumberBlocks(refs.itemList); refs.formatTypeSelect.value = 'hg-hk'; refs.formPengajuan.classList.remove('js-format-polos'); tutupModal([refs.modalRiwayat], refs.modalOverlay); showCustomAlert('Data pengajuan berhasil dimuat!'); }
    function toggleTema(tombolTemaRef) { if(!tombolTemaRef) return; const body = document.body; body.classList.toggle('dark-mode'); if (body.classList.contains('dark-mode')) { localStorage.setItem(KEY_TEMA, 'dark'); tombolTemaRef.textContent = '🌙'; } else { localStorage.setItem(KEY_TEMA, 'light'); tombolTemaRef.textContent = '☀️'; } }

    // --- 4. Fungsi Inisialisasi Aplikasi Utama ---
    async function initializeApp() {
        console.log("Initializing app...");
        const formPengajuan = document.getElementById('form-pengajuan'); const formatTypeSelect = document.getElementById('tipe-format'); const itemList = document.getElementById('item-list'); const tambahBarangBtn = document.getElementById('tambah-barang-btn'); const hasilTeks = document.getElementById('hasil-teks'); const hasilOutputSection = document.getElementById('hasil-output'); const tombolCopy = document.getElementById('tombol-copy'); const tanggalInput = document.getElementById('tanggal'); const generateBtn = document.getElementById('generate-btn'); const marketingInput = document.getElementById('marketing'); const kkaInput = document.getElementById('kka'); const namaTokoInput = document.getElementById('nama-toko'); const wilayahInput = document.getElementById('wilayah'); const tombolTema = document.getElementById('tombol-tema'); const tombolPengaturan = document.getElementById('tombol-pengaturan'); const tombolRiwayat = document.getElementById('tombol-riwayat'); const modalOverlay = document.getElementById('modal-overlay'); const modalPengaturan = document.getElementById('modal-pengaturan'); const simpanPengaturanBtn = document.getElementById('simpan-pengaturan-btn'); const namaSalesInput = document.getElementById('nama-sales-default'); const modalRiwayat = document.getElementById('modal-riwayat'); const riwayatList = document.getElementById('riwayat-list'); const hapusRiwayatBtn = document.getElementById('hapus-riwayat-btn'); const semuaTombolTutup = document.querySelectorAll('.tombol-tutup-modal'); const tombolWA = document.getElementById('tombol-whatsapp'); const nomorWaInput = document.getElementById('nomor-wa-direktur'); const riwayatSearchInput = document.getElementById('riwayat-search-input');
        const refs = { formPengajuan, formatTypeSelect, itemList, hasilTeks, hasilOutputSection, tombolCopy, tanggalInput, generateBtn, marketingInput, kkaInput, namaTokoInput, wilayahInput, modalOverlay, modalPengaturan, namaSalesInput, nomorWaInput, modalRiwayat, riwayatList, riwayatSearchInput };
        if (!formPengajuan || !itemList || !generateBtn || !tombolTema || !tombolPengaturan || !tombolRiwayat || !tanggalInput || !marketingInput || !namaSalesInput || !nomorWaInput) { console.error("Error: Elemen UI penting tidak ditemukan! Cek HTML ID."); if(loadingPage) loadingPage.innerHTML = "<p style='font-family: sans-serif; color: red; text-align: center;'>Error memuat aplikasi!<br>Cek ID elemen HTML.</p>"; return; }
        loadPengaturan(marketingInput, namaSalesInput, nomorWaInput, tanggalInput);
        try { const dbLoaded = await loadDatabase(generateBtn); if (dbLoaded && itemList && itemList.children.length === 0) { tambahBarang(itemList); } else if (!dbLoaded) { console.error("Inisialisasi dihentikan karena database tidak bisa dimuat."); if(itemList) itemList.innerHTML = "<p style='color:red; text-align:center;'>Gagal memuat data produk.</p>"; return; }
        } catch (error) { console.error("Inisialisasi dihentikan karena database error:", error.message); if(itemList) itemList.innerHTML = "<p style='color:red; text-align:center;'>Gagal memuat data produk.</p>"; return; } // Error sudah di-alert di loadDatabase
        formPengajuan.addEventListener('submit', (e) => generateTeks(e, refs));
        tombolCopy.addEventListener('click', () => copyTeks(hasilTeks, tombolCopy));
        tombolWA.addEventListener('click', () => kirimViaWA(hasilTeks));
        tambahBarangBtn.addEventListener('click', () => tambahBarang(itemList));
        itemList.addEventListener('click', (e) => hapusBlokBarang(e, itemList));
        tombolTema.addEventListener('click', () => toggleTema(tombolTema));
        tombolPengaturan.addEventListener('click', () => { loadPengaturan(marketingInput, namaSalesInput, nomorWaInput, tanggalInput); bukaModal(modalPengaturan, modalOverlay); });
        tombolRiwayat.addEventListener('click', () => { if(riwayatSearchInput) riwayatSearchInput.value = ""; tampilkanRiwayat("", riwayatList); bukaModal(modalRiwayat, modalOverlay); });
        formatTypeSelect.addEventListener('change', (e) => { if (e.target.value === 'image-format') { formPengajuan.classList.add('js-format-polos'); } else { formPengajuan.classList.remove('js-format-polos'); } });
        const modalsToClose = [modalPengaturan, modalRiwayat];
        modalOverlay.addEventListener('click', () => tutupModal(modalsToClose, modalOverlay));
        semuaTombolTutup.forEach(tombol => tombol.addEventListener('click', () => tutupModal(modalsToClose, modalOverlay)));
        simpanPengaturanBtn.addEventListener('click', () => simpanPengaturan(namaSalesInput, nomorWaInput, marketingInput, modalPengaturan, modalOverlay));
        hapusRiwayatBtn.addEventListener('click', () => hapusSemuaRiwayat(riwayatList));
        riwayatList.addEventListener('click', async (e) => { if (e.target.classList.contains('tombol-hapus-item')) { e.stopPropagation(); const id = e.target.dataset.id; const confirmed = await showCustomConfirm('Hapus item riwayat ini?'); if (confirmed) { hapusItemRiwayat(id, riwayatSearchInput, riwayatList); } } else { const riwayatItem = e.target.closest('.riwayat-item'); if (riwayatItem) { const id = riwayatItem.dataset.id; const muatRefs = { namaTokoInput, wilayahInput, kkaInput, tanggalInput, marketingInput, itemList, formatTypeSelect, formPengajuan, modalRiwayat, modalOverlay }; muatDariRiwayat(id, muatRefs); } } });
        riwayatSearchInput.addEventListener('input', (e) => tampilkanRiwayat(e.target.value, riwayatList));
        itemList.addEventListener('input', (e) => { if (e.target.classList.contains('nama-barang-search')) { const searchTerm = e.target.value; const searchContainer = e.target.closest('.search-container'); if(searchContainer) { const resultsContainer = searchContainer.querySelector('.search-results'); if(resultsContainer) tampilkanHasilPencarian(searchTerm, resultsContainer); } } });
        itemList.addEventListener('click', (e) => { if (e.target.classList.contains('result-item')) { const selectedValue = e.target.dataset.value; const itemBlock = e.target.closest('.card--item'); const resultsContainer = e.target.closest('.search-results'); if (itemBlock && resultsContainer && selectedValue !== undefined) { updateTampilanBarang(itemBlock, selectedValue); resultsContainer.classList.add('hidden'); } else { console.error("Gagal update tampilan barang, elemen tidak ditemukan atau value kosong", {itemBlock, resultsContainer, selectedValue}); } } });
        document.addEventListener('click', (e) => { if (!e.target.closest('.search-container')) { document.querySelectorAll('.search-results').forEach(div => { div.classList.add('hidden'); }); } });
        document.body.classList.add('loaded');
        document.querySelectorAll('.app-header, .container, .pixel-art-footer').forEach(el => { setTimeout(() => el.classList.remove('content-hidden'), 50); });
        console.log("App initialized successfully.");
    }

    // --- 5. Atur Timeout untuk Loading Screen ---
    const loadingDuration = 2500;
    setTimeout(() => {
        if (loadingPage) { loadingPage.classList.add('hidden'); }
        initializeApp();
    }, loadingDuration);

}); // <-- AKHIR DARI DOMContentLoaded
